#############################################################################
# Makefile for building: cifers
# Generated by qmake (2.01a) (Qt 4.8.3) on: ?? ???. 31 17:38:47 2014
# Project:  cifers.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile cifers.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		cezar.cpp \
		vigenere.cpp \
		stegano.cpp \
		des.cpp moc_mainwindow.cpp \
		moc_cezar.cpp \
		moc_vigenere.cpp \
		moc_stegano.cpp \
		moc_des.cpp
OBJECTS       = main.o \
		mainwindow.o \
		cezar.o \
		vigenere.o \
		stegano.o \
		des.o \
		moc_mainwindow.o \
		moc_cezar.o \
		moc_vigenere.o \
		moc_stegano.o \
		moc_des.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		cifers.pro
QMAKE_TARGET  = cifers
DESTDIR       = 
TARGET        = cifers

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_cezar.h ui_vigenere.h ui_stegano.h ui_des.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cifers.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile cifers.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile cifers.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/cifers1.0.0 || $(MKDIR) .tmp/cifers1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/cifers1.0.0/ && $(COPY_FILE) --parents mainwindow.h cezar.h vigenere.h stegano.h des.h des.h .tmp/cifers1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp cezar.cpp vigenere.cpp stegano.cpp des.cpp .tmp/cifers1.0.0/ && $(COPY_FILE) --parents mainwindow.ui cezar.ui vigenere.ui stegano.ui des.ui .tmp/cifers1.0.0/ && (cd `dirname .tmp/cifers1.0.0` && $(TAR) cifers1.0.0.tar cifers1.0.0 && $(COMPRESS) cifers1.0.0.tar) && $(MOVE) `dirname .tmp/cifers1.0.0`/cifers1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/cifers1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_cezar.cpp moc_vigenere.cpp moc_stegano.cpp moc_des.cpp moc_des.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_cezar.cpp moc_vigenere.cpp moc_stegano.cpp moc_des.cpp moc_des.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_cezar.cpp: cezar.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cezar.h -o moc_cezar.cpp

moc_vigenere.cpp: vigenere.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) vigenere.h -o moc_vigenere.cpp

moc_stegano.cpp: stegano.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) stegano.h -o moc_stegano.cpp

moc_des.cpp: des.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) des.h -o moc_des.cpp

moc_des.cpp: des.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) des.h -o moc_des.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_cezar.h ui_vigenere.h ui_stegano.h ui_des.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_cezar.h ui_vigenere.h ui_stegano.h ui_des.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_cezar.h: cezar.ui
	/usr/bin/uic-qt4 cezar.ui -o ui_cezar.h

ui_vigenere.h: vigenere.ui
	/usr/bin/uic-qt4 vigenere.ui -o ui_vigenere.h

ui_stegano.h: stegano.ui
	/usr/bin/uic-qt4 stegano.ui -o ui_stegano.h

ui_des.h: des.ui
	/usr/bin/uic-qt4 des.ui -o ui_des.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		cezar.h \
		vigenere.h \
		stegano.h \
		des.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

cezar.o: cezar.cpp cezar.h \
		ui_cezar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cezar.o cezar.cpp

vigenere.o: vigenere.cpp vigenere.h \
		ui_vigenere.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vigenere.o vigenere.cpp

stegano.o: stegano.cpp stegano.h \
		ui_stegano.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stegano.o stegano.cpp

des.o: des.cpp des.h \
		ui_des.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o des.o des.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_cezar.o: moc_cezar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cezar.o moc_cezar.cpp

moc_vigenere.o: moc_vigenere.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vigenere.o moc_vigenere.cpp

moc_stegano.o: moc_stegano.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stegano.o moc_stegano.cpp

moc_des.o: moc_des.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_des.o moc_des.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

